Repository 1teamPJ/Mohaeng, pull requests merged in 2024-05, with the labels that each got.

#17 Route설정 완료 #16
  MohanengPJ/mohanengpj/src/components/Front.js
  MohanengPJ/mohanengpj/src/layouts/Layout.js
  MohanengPJ/mohanengpj/src/pages/CheckBoard.js
  mohanengpj/mohanengpj/src/App.js
Labels: ⚡Feature

#22 #21 travelboard -> dev pr
  MohanengPJ/mohanengpj/src/css/travelstyle.css
  MohanengPJ/mohanengpj/src/img/busan.jpg
  MohanengPJ/mohanengpj/src/img/chuncheon.jpg
  MohanengPJ/mohanengpj/src/img/gangneung.jpg
  MohanengPJ/mohanengpj/src/img/gyeongju.jpg
  MohanengPJ/mohanengpj/src/img/incheon.jpg
  MohanengPJ/mohanengpj/src/img/jeju.jpg
  MohanengPJ/mohanengpj/src/img/jeonju.jpg
  MohanengPJ/mohanengpj/src/img/seoul.jpg
  MohanengPJ/mohanengpj/src/img/yeosu.jpg
  MohanengPJ/mohanengpj/src/pages/TravelRecommandations.js
  mohanengpj/mohanengpj/src/App.js
Labels: ⚡Feature, ✨PR

#24 #19 CBboard main 연결
  MohanengPJ/mohanengpj/src/layouts/CbLayout.js
  MohanengPJ/mohanengpj/src/pages/CBfooter.js
  MohanengPJ/mohanengpj/src/pages/CBheader.js
  MohanengPJ/mohanengpj/src/pages/CBlist.js
  MohanengPJ/mohanengpj/src/pages/CBstyle.css
  MohanengPJ/mohanengpj/src/pages/CheckBoard.js
  mohanengpj/mohanengpj/src/App.js
Labels: ⚡Feature, ✨PR

#29 Mohaeng/checkboard3
  MohanengPJ/mohanengpj/src/pages/CBfooter.js
  MohanengPJ/mohanengpj/src/pages/CBlist.js
  MohanengPJ/mohanengpj/src/pages/CBstyle.css
Labels: ✨PR

#32 [Mohaeng/main2] -> [Mohaeng/dev]] PR
  MohanengPJ/mohanengpj/src/img/houseimg/house1.webp
  MohanengPJ/mohanengpj/src/img/houseimg/house2.webp
  MohanengPJ/mohanengpj/src/img/houseimg/house3.webp
  MohanengPJ/mohanengpj/src/img/houseimg/house4.webp
  MohanengPJ/mohanengpj/src/img/houseimg/house5.webp
  MohanengPJ/mohanengpj/src/layouts/Layout.js
  MohanengPJ/mohanengpj/src/pages/Swiper.js
  MohanengPJ/mohanengpj/src/pages/style.css
  mohanengpj/mohanengpj/package-lock.json
  mohanengpj/mohanengpj/package.json
Labels: ✨PR

#39 [dev/main] -> [main] PR
  MohanengPJ/mohanengpj/src/pages/Header.js
Labels: ✨PR

#41 #40 Mohaeng/main3
  MohanengPJ/mohanengpj/src/components/Front.js
  MohanengPJ/mohanengpj/src/components/Front.module.css
  MohanengPJ/mohanengpj/src/css/travelstyle.css
  MohanengPJ/mohanengpj/src/img/mainlogo1.png
  MohanengPJ/mohanengpj/src/img/mainlogo2.png
  MohanengPJ/mohanengpj/src/img/mainlogo3.png
  MohanengPJ/mohanengpj/src/img/mainlogo4.png
  MohanengPJ/mohanengpj/src/img/mainlogo5.png
  MohanengPJ/mohanengpj/src/img/mainlogo6.png
  MohanengPJ/mohanengpj/src/img/mohaenglogo.png
  MohanengPJ/mohanengpj/src/pages/Recommend.js
  MohanengPJ/mohanengpj/src/pages/recommend.css
  MohanengPJ/mohanengpj/src/pages/style.css
  mohanengpj/mohanengpj/public/index.html
Labels: ✨PR

#43 #42 질문 오타 수정
  MohanengPJ/mohanengpj/src/pages/CBfooter.js
  MohanengPJ/mohanengpj/src/pages/CBlist.js
Labels: modication

#44 Update README.md
  README.md
Labels: README

#45 Update README.md
  README.md
Labels: README

#50 Update README.md
  README.md
Labels: README
